In [14]:
import os
import requests
from dotenv import load_dotenv
import pandas as pd

load_dotenv("../.env")

client_id = os.getenv("TWITCH_CLIENT_ID")
client_secret = os.getenv("TWITCH_CLIENT_SECRET")

token_response = requests.post(
    "https://id.twitch.tv/oauth2/token",
    data={
        "client_id": client_id,
        "client_secret": client_secret,
        "grant_type": "client_credentials"
    }
)

access_token = token_response.json()["access_token"]

In [7]:
headers = {
    "Client-ID": client_id,
    "Authorization": f"Bearer {access_token}"
}

response = requests.get(
    "https://api.twitch.tv/helix/users",
    headers=headers,
    params={"login": "classictetris"}
)

response.status_code, response.json()

(200,
 {'data': [{'id': '131454884',
    'login': 'classictetris',
    'display_name': 'ClassicTetris',
    'type': '',
    'broadcaster_type': 'partner',
    'description': 'Home of the Classic Tetris World Championship since 2010. Love what you see? Support our grassroots team and future events. Every donation helps! http://bit.ly/donatectwc\t',
    'profile_image_url': 'https://static-cdn.jtvnw.net/jtv_user_pictures/c7669a41-3dd4-4618-8b6f-a76776ac2893-profile_image-300x300.png',
    'offline_image_url': 'https://static-cdn.jtvnw.net/jtv_user_pictures/3a332843cd0b53cd-channel_offline_image-1920x1080.png',
    'view_count': 0,
    'created_at': '2016-08-06T01:30:38Z'}]})

In [8]:
broadcaster_id = "131454884"

videos_response = requests.get(
    "https://api.twitch.tv/helix/videos",
    headers=headers,
    params={
        "user_id": broadcaster_id,
        "first": 100
    }
)

videos_response.status_code, videos_response.json()

(200,
 {'data': [{'id': '2730129007',
    'stream_id': '318490941147',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'MONDAY NIGHT MAYHEM | HOSTED BY OMENVOIR',
    'description': '',
    'created_at': '2026-03-23T23:01:55Z',
    'published_at': '2026-03-23T23:01:55Z',
    'url': 'https://www.twitch.tv/videos/2730129007',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/3457bfbecc7143ed60d3_classictetris_318490941147_1774306910//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 888,
    'language': 'en',
    'type': 'archive',
    'duration': '2h31m33s',
    'muted_segments': None},
   {'id': '2727505425',
    'stream_id': '316689921765',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'FRIDAY NIGHT FIGHTS  VOL. 2 EPISODE 62 | CTWC TORONTO SPECIAL | HOSTED BY BIRBWIZARD',
    'description': '',
    'created_at': '2026-03-20T21:57:04Z',
    'published_at': '2026-03-20T21:57:04Z',
    'url': 'https://www.twitch.tv/videos/2727505425',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d3fi1amfgojobc/8686cdb8c347aa5d41e2_classictetris_316689921765_1774043816//thumb/thumb1-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 2011,
    'language': 'en',
    'type': 'archive',
    'duration': '5h25m43s',
    'muted_segments': None},
   {'id': '2722223193',
    'stream_id': '318150256857',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC PHOENIX 2026 REGIONAL DAY 2 | QUALIFYING & TOURNAMENT | !MATCHERINO !DONATE',
    'description': '',
    'created_at': '2026-03-14T16:28:53Z',
    'published_at': '2026-03-14T16:28:53Z',
    'url': 'https://www.twitch.tv/videos/2722223193',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/c90d9de7280f1181f7a0_classictetris_318150256857_1773505729//thumb/thumb1-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 4103,
    'language': 'en',
    'type': 'archive',
    'duration': '9h16m25s',
    'muted_segments': None},
   {'id': '2721571324',
    'stream_id': '318199817050',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC PHOENIX 2026 REGIONAL DAY 1 | SIDE EVENTS | !MATCHERINO !DONATE',
    'description': '',
    'created_at': '2026-03-13T21:50:42Z',
    'published_at': '2026-03-13T21:50:42Z',
    'url': 'https://www.twitch.tv/videos/2721571324',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/490e6f8a1b632119d221_classictetris_318199817050_1773438638//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1249,
    'language': 'en',
    'type': 'archive',
    'duration': '3h9m29s',
    'muted_segments': None},
   {'id': '2719900057',
    'stream_id': '318166669658',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'SQUARE UP VOL. 2 EPISODE 1 | HOSTED BY IANKEITH',
    'description': '',
    'created_at': '2026-03-11T21:56:02Z',
    'published_at': '2026-03-11T21:56:02Z',
    'url': 'https://www.twitch.tv/videos/2719900057',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/86fa60a59b5caef677d0_classictetris_318166669658_1773266138//thumb/thumb1-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 904,
    'language': 'en',
    'type': 'archive',
    'duration': '3h33m26s',
    'muted_segments': None},
   {'id': '2718267699',
    'stream_id': '318068095833',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'MONDAY NIGHT MAYHEM VOL. 2 EPISODE 71 | HOSTED BY COLIN',
    'description': '',
    'created_at': '2026-03-09T22:01:20Z',
    'published_at': '2026-03-09T22:01:20Z',
    'url': 'https://www.twitch.tv/videos/2718267699',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/8eeb492d9587e16b51e3_classictetris_318068095833_1773093675//thumb/thumb1-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1414,
    'language': 'en',
    'type': 'archive',
    'duration': '4h25m29s',
    'muted_segments': None},
   {'id': '2715682655',
    'stream_id': '318007540441',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'FRIDAY NIGHT FIGHTS VOL. 2 EPISODE 61 | HOSTED BY KINGSMAN',
    'description': '',
    'created_at': '2026-03-06T23:40:21Z',
    'published_at': '2026-03-06T23:40:21Z',
    'url': 'https://www.twitch.tv/videos/2715682655',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/e4e23240dbe81093ddd9_classictetris_318007540441_1772840416//thumb/thumb1-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1692,
    'language': 'en',
    'type': 'archive',
    'duration': '4h1m54s',
    'muted_segments': None},
   {'id': '2712331151',
    'stream_id': '317508052316',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'MONDAY NIGHT MAYHEM VOL. 2 EPISODE 70 | HOSTED BY OMENVOIR',
    'description': '',
    'created_at': '2026-03-03T01:03:40Z',
    'published_at': '2026-03-03T01:03:40Z',
    'url': 'https://www.twitch.tv/videos/2712331151',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d2vi6trrdongqn/5c66c198e3cb8db7914e_classictetris_317508052316_1772499815//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1609,
    'language': 'en',
    'type': 'archive',
    'duration': '3h58m34s',
    'muted_segments': None},
   {'id': '2710790062',
    'stream_id': None,
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': '2026 CTWC Austria Regional - Qualifying Session 5',
    'description': '',
    'created_at': '2026-03-01T06:43:19Z',
    'published_at': '2026-03-01T06:43:19Z',
    'url': 'https://www.twitch.tv/videos/2710790062',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/498d62fc851ac3db6f21_classictetris_50983975148_7923896674//thumb/thumb2710790062-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 13,
    'language': 'en',
    'type': 'highlight',
    'duration': '1h11m0s',
    'muted_segments': None},
   {'id': '2709946617',
    'stream_id': '318075365595',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC AUSTRIA 2026 REGIONAL DAY 2 | !MATCHERINO !BRACKET !QUAL !DONATE',
    'description': '',
    'created_at': '2026-02-28T11:27:40Z',
    'published_at': '2026-02-28T11:27:40Z',
    'url': 'https://www.twitch.tv/videos/2709946617',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/f70b840e880b10ead7e6_classictetris_318075365595_1772278055//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 7153,
    'language': 'en',
    'type': 'archive',
    'duration': '11h29m46s',
    'muted_segments': None},
   {'id': '2709538340',
    'stream_id': None,
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': '2026 CTWC Austria Regional - Qualifying Session 4',
    'description': '',
    'created_at': '2026-02-28T00:13:27Z',
    'published_at': '2026-02-28T00:13:27Z',
    'url': 'https://www.twitch.tv/videos/2709538340',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/d49ffe93062819054028_classictetris_75595335706_3879414279//thumb/thumb2709538340-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 19,
    'language': 'en',
    'type': 'highlight',
    'duration': '1h10m17s',
    'muted_segments': None},
   {'id': '2709526960',
    'stream_id': None,
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': '2026 CTWC Austria Regional - Qualifying Session 3',
    'description': '',
    'created_at': '2026-02-28T00:00:58Z',
    'published_at': '2026-02-28T00:00:58Z',
    'url': 'https://www.twitch.tv/videos/2709526960',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/c7cbed0e569c2effd945_classictetris_40184729051_6944147185//thumb/thumb2709526960-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 3,
    'language': 'en',
    'type': 'highlight',
    'duration': '1h9m0s',
    'muted_segments': None},
   {'id': '2709520152',
    'stream_id': None,
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': '2026 CTWC Austria Regional - Qualifying Session 2',
    'description': '',
    'created_at': '2026-02-27T23:53:54Z',
    'published_at': '2026-02-27T23:53:54Z',
    'url': 'https://www.twitch.tv/videos/2709520152',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/4609b9ecd570e349f008_classictetris_42958754460_1674658821//thumb/thumb2709520152-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 2,
    'language': 'en',
    'type': 'highlight',
    'duration': '1h10m24s',
    'muted_segments': None},
   {'id': '2709516499',
    'stream_id': None,
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': '2026 CTWC Austria Regional - Qualifying Session 1',
    'description': '',
    'created_at': '2026-02-27T23:49:15Z',
    'published_at': '2026-02-27T23:49:15Z',
    'url': 'https://www.twitch.tv/videos/2709516499',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/8a8dae8df8df47dd0f0c_classictetris_60683248057_8525744353//thumb/thumb2709516499-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 2,
    'language': 'en',
    'type': 'highlight',
    'duration': '49m0s',
    'muted_segments': None},
   {'id': '2709495753',
    'stream_id': '317873633113',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'FRIDAY NIGHT FIGHTS VOL. 2 EPISODE 60 | FAVE FIVE 2026 REVEALS! HOSTED BY KINGSMAN',
    'description': '',
    'created_at': '2026-02-27T23:23:02Z',
    'published_at': '2026-02-27T23:23:02Z',
    'url': 'https://www.twitch.tv/videos/2709495753',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/4ed694b4e1f455db2818_classictetris_317873633113_1772234577//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1795,
    'language': 'en',
    'type': 'archive',
    'duration': '3h48m30s',
    'muted_segments': None},
   {'id': '2709073474',
    'stream_id': '317866596313',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC AUSTRIA 2026 REGIONAL DAY 1 | !MATCHERINO !BRACKET !QUAL !DONATE',
    'description': '',
    'created_at': '2026-02-27T14:30:37Z',
    'published_at': '2026-02-27T14:30:37Z',
    'url': 'https://www.twitch.tv/videos/2709073474',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/66a50e35dccab886207b_classictetris_317866596313_1772202632//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 2513,
    'language': 'en',
    'type': 'archive',
    'duration': '5h24m30s',
    'muted_segments': None},
   {'id': '2704036263',
    'stream_id': '317761271257',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'TETRIS FRIENDLIES REVOLUTION 2026 NIGHT 2 | HOSTED BY KINGSMAN',
    'description': '',
    'created_at': '2026-02-21T19:50:51Z',
    'published_at': '2026-02-21T19:50:51Z',
    'url': 'https://www.twitch.tv/videos/2704036263',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/2dc7b3a1d49ab2077b09_classictetris_317761271257_1771703445//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 3874,
    'language': 'en',
    'type': 'archive',
    'duration': '5h7m19s',
    'muted_segments': None},
   {'id': '2703382418',
    'stream_id': '317746611545',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'TETRIS FRIENDLIES REVOLUTION 2026 NIGHT 1 - PART 2 | HOSTED BY COLIN',
    'description': '',
    'created_at': '2026-02-21T01:51:34Z',
    'published_at': '2026-02-21T01:51:34Z',
    'url': 'https://www.twitch.tv/videos/2703382418',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/b4553e8ecbf53f3c1393_classictetris_317746611545_1771638689//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1770,
    'language': 'en',
    'type': 'archive',
    'duration': '3h25m54s',
    'muted_segments': None},
   {'id': '2703256233',
    'stream_id': '317743568857',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'TETRIS FRIENDLIES REVOLUTION 2026 NIGHT 1 - PART 1 | HOSTED BY COLIN',
    'description': '',
    'created_at': '2026-02-20T23:20:12Z',
    'published_at': '2026-02-20T23:20:12Z',
    'url': 'https://www.twitch.tv/videos/2703256233',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/e77d896c0e479e2e7ea5_classictetris_317743568857_1771629607//thumb/thumb1-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1579,
    'language': 'en',
    'type': 'archive',
    'duration': '2h31m15s',
    'muted_segments': None},
   {'id': '2699760669',
    'stream_id': '317667511129',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'MONDAY NIGHT MAYHEM VOL. 2 EPISODE 69 | HOSTED BY COLIN',
    'description': '',
    'created_at': '2026-02-16T22:55:57Z',
    'published_at': '2026-02-16T22:55:57Z',
    'url': 'https://www.twitch.tv/videos/2699760669',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/9479b9229ac260ef33b5_classictetris_317667511129_1771282551//thumb/thumb1-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1905,
    'language': 'en',
    'type': 'archive',
    'duration': '4h37m26s',
    'muted_segments': None},
   {'id': '2697759668',
    'stream_id': '317847904475',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC GENESIS X3 OPEN CHAMPIONSHIP | !MATCHERINO !BRACKET !QUAL !DONATE',
    'description': '',
    'created_at': '2026-02-14T18:31:25Z',
    'published_at': '2026-02-14T18:31:25Z',
    'url': 'https://www.twitch.tv/videos/2697759668',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/b4ef1a348e9eb4c4dc60_classictetris_317847904475_1771093881//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 8350,
    'language': 'en',
    'type': 'archive',
    'duration': '11h0m30s',
    'muted_segments': None},
   {'id': '2696825978',
    'stream_id': '317683530714',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC GENESIS X3 DAS CHAMPIONSHIP | !MATCHERINO !BRACKET !QUAL !DONATE',
    'description': '',
    'created_at': '2026-02-13T18:26:39Z',
    'published_at': '2026-02-13T18:26:39Z',
    'url': 'https://www.twitch.tv/videos/2696825978',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/ec06d41b4ef57ae1ab71_classictetris_317683530714_1771007194//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 6248,
    'language': 'en',
    'type': 'archive',
    'duration': '9h59m7s',
    'muted_segments': None},
   {'id': '2693640778',
    'stream_id': '317621809498',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'MONDAY NIGHT MAYHEM VOL. 2 EPISODE 68 | HOSTED BY OMENVOIR',
    'description': '',
    'created_at': '2026-02-10T00:01:44Z',
    'published_at': '2026-02-10T00:01:44Z',
    'url': 'https://www.twitch.tv/videos/2693640778',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/b354d43ae50b448cc251_classictetris_317621809498_1770681698//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1221,
    'language': 'en',
    'type': 'archive',
    'duration': '4h18m3s',
    'muted_segments': None},
   {'id': '2691655452',
    'stream_id': '317717619291',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC Washington State 2026 Regional Day 2 | !matcherino !bracket !qual !donate',
    'description': '',
    'created_at': '2026-02-07T18:28:28Z',
    'published_at': '2026-02-07T18:28:28Z',
    'url': 'https://www.twitch.tv/videos/2691655452',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/8f4a0c90e1cb9f694c4c_classictetris_317717619291_1770488903//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 3998,
    'language': 'en',
    'type': 'archive',
    'duration': '8h3m19s',
    'muted_segments': None},
   {'id': '2690917678',
    'stream_id': '317563872858',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'CTWC Washington State 2026 Regional Day 1 | !matcherino !bracket !qual !donate',
    'description': '',
    'created_at': '2026-02-06T22:49:47Z',
    'published_at': '2026-02-06T22:49:47Z',
    'url': 'https://www.twitch.tv/videos/2690917678',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/539d60ba9fa448f62189_classictetris_317563872858_1770418182//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1524,
    'language': 'en',
    'type': 'archive',
    'duration': '4h9m58s',
    'muted_segments': None},
   {'id': '2684684099',
    'stream_id': '317558362587',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'FRIDAY NIGHT FIGHTS VOL. 2 EPISODE 59 | HOSTED BY BIRBWIZARD',
    'description': '',
    'created_at': '2026-01-30T22:58:35Z',
    'published_at': '2026-01-30T22:58:35Z',
    'url': 'https://www.twitch.tv/videos/2684684099',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/35f57c71abd8d2b8894a_classictetris_317558362587_1769813910//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1579,
    'language': 'en',
    'type': 'archive',
    'duration': '6h5m36s',
    'muted_segments': None},
   {'id': '2681191468',
    'stream_id': '317300377305',
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'MONDAY NIGHT MAYHEM VOL. 2 EPISODE 67 | HOSTED BY OMENVOIR',
    'description': '',
    'created_at': '2026-01-27T00:01:51Z',
    'published_at': '2026-01-27T00:01:51Z',
    'url': 'https://www.twitch.tv/videos/2681191468',
    'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/c7d9a9f535cd7be42cda_classictetris_317300377305_1769472106//thumb/thumb0-%{width}x%{height}.jpg',
    'viewable': 'public',
    'view_count': 1306,
    'language': 'en',
    'type': 'archive',
    'duration': '4h34m38s',
    'muted_segments': None},
   {'id': '2595692157',
    'stream_id': None,
    'user_id': '131454884',
    'user_login': 'classictetris',
    'user_name': 'ClassicTetris',
    'title': 'Kingsman and Vince Clemente Get Pied in the Face - 2025 Jonas Neubauer Cup',
    'description': '',
    'created_at': '2025-10-19T04:33:31Z',
    'published_at': '2025-10-19T04:33:31Z',
    'url': 'https://www.twitch.tv/videos/2595692157',

In [ ]:
all_videos = []len(all_videos)
cursor = None

while True:
    params = {
        "user_id": broadcaster_id,
        "first": 100
    }
    
    if cursor:
        params["after"] = cursor

    response = requests.get(
        "https://api.twitch.tv/helix/videos",
        headers=headers,
        params=params
    )
    response.raise_for_status()
    
    data = response.json()
    all_videos.extend(data["data"])
    
    cursor = data.get("pagination", {}).get("cursor")
    if not cursor:
        break

len(all_videos)

46

In [10]:
len(all_videos)

46

In [11]:
all_videos[0].keys()

dict_keys(['id', 'stream_id', 'user_id', 'user_login', 'user_name', 'title', 'description', 'created_at', 'published_at', 'url', 'thumbnail_url', 'viewable', 'view_count', 'language', 'type', 'duration', 'muted_segments'])

In [15]:
videos_df = pd.DataFrame(all_videos)
videos_df[["created_at", "title", "type", "view_count", "url"]].head(10)

,created_at,title,type,view_count,url
0,2026-03-23T23:01:55Z,MONDAY NIGHT MAYHEM | HOSTED BY OMENVOIR,archive,890,https://www.twitch.tv/videos/2730129007
1,2026-03-20T21:57:04Z,FRIDAY NIGHT FIGHTS VOL. 2 EPISODE 62 | CTWC ...,archive,2011,https://www.twitch.tv/videos/2727505425
2,2026-03-14T16:28:53Z,CTWC PHOENIX 2026 REGIONAL DAY 2 | QUALIFYING ...,archive,4103,https://www.twitch.tv/videos/2722223193
3,2026-03-13T21:50:42Z,CTWC PHOENIX 2026 REGIONAL DAY 1 | SIDE EVENTS...,archive,1249,https://www.twitch.tv/videos/2721571324
4,2026-03-11T21:56:02Z,SQUARE UP VOL. 2 EPISODE 1 | HOSTED BY IANKEITH,archive,904,https://www.twitch.tv/videos/2719900057
5,2026-03-09T22:01:20Z,MONDAY NIGHT MAYHEM VOL. 2 EPISODE 71 | HOSTED...,archive,1414,https://www.twitch.tv/videos/2718267699
6,2026-03-06T23:40:21Z,FRIDAY NIGHT FIGHTS VOL. 2 EPISODE 61 | HOSTED...,archive,1692,https://www.twitch.tv/videos/2715682655
7,2026-03-03T01:03:40Z,MONDAY NIGHT MAYHEM VOL. 2 EPISODE 70 | HOSTED...,archive,1609,https://www.twitch.tv/videos/2712331151
8,2026-03-01T06:43:19Z,2026 CTWC Austria Regional - Qualifying Session 5,highlight,13,https://www.twitch.tv/videos/2710790062
9,2026-02-28T11:27:40Z,CTWC AUSTRIA 2026 REGIONAL DAY 2 | !MATCHERINO...,archive,7153,https://www.twitch.tv/videos/2709946617

In [16]:
videos_df[["created_at", "title", "type", "view_count", "url"]].tail(10)

,created_at,title,type,view_count,url
36,2024-06-10T07:11:46Z,zzz Classic Tetris World Championship XV – Day...,highlight,175,https://www.twitch.tv/videos/2168328747
37,2024-06-08T06:16:00Z,HISTORIC TETRIS MOMENT | ModRetro Classic Tetr...,highlight,153,https://www.twitch.tv/videos/2166592438
38,2024-02-09T07:54:18Z,"Race to 10 Million! Blue Scuti, Andy, Fractal,...",highlight,9,https://www.twitch.tv/videos/2057582369
39,2024-01-04T04:47:53Z,Game Crash Chase | Who will BEAT Tetris next?,highlight,66,https://www.twitch.tv/videos/2022235875
40,2023-10-16T01:11:29Z,CTWC 2023 Day 3: Gold Bracket Top 16 thru Finals,highlight,1741,https://www.twitch.tv/videos/1952196127
41,2022-10-21T02:36:36Z,Boom Trophy for Tang,highlight,158,https://www.twitch.tv/videos/1629986663
42,2022-10-17T01:01:37Z,CTWC 2022 Day 3 - Gold Bracket Finals,highlight,1359,https://www.twitch.tv/videos/1626411847
43,2019-11-06T14:06:05Z,CTWC 2019 - Greentea vs Joseph,highlight,1513,https://www.twitch.tv/videos/504674253
44,2019-10-22T21:39:19Z,"Paul ""MegaRetroMan"" Tesi defeats Jonas Neubaue...",highlight,1929,https://www.twitch.tv/videos/498194386
45,2018-10-28T07:56:38Z,Insane Quick Tap by Greentea in Semifinal!,highlight,3656,https://www.twitch.tv/videos/328436649

In [17]:
videos_df.to_csv("../data/raw/twitch_api_videos_raw.csv", index=False)